#include<stdio.h>
#include<stdlib.h>
int main(void)
{
    unsigned long long int n,count=0,i,x,dummy,temp,temp1;
    scanf("%llu",&n);
    x=n;
    if(n>0)
    {
        if(n%10!=0&&n>10)
        {
            for(i=1;i<100000000000;i++)
            {
                x/=10;
                if(x==0)
                {
                    break;
                }
            }
            x=i;
            do
            {
                for(i=0,dummy=1;i<x-1;i++)
                {
                    dummy*=10;
                }
                temp=n/dummy;
                if(temp==4||temp==7)
                {
                    count++;
                }
                n=n-temp*dummy;
                if(n<10)
                {
                    if(n==4||n==7)
                    {
                        count++;
                        break;
                    }
                    else
                    {
                        break;
                    }
                }
                x--;
            }while(x>=0);
        }
        else if(n<10)
        {
            if(n==4||n==7)
            {
                count++;
            }
        }
    }
    else
    {
        printf("NO");
        exit(0);
    }
    temp1=count;
    for(i=1;i<100000000000;i++)
    {
        temp1/=10;
        if(temp1==0)
        {
            break;
        }
    }
    x=i;
    if(count%10!=0&&n>10)
    {
        printf("if eo dhukse.\n");
        do
        {
            for(i=0,dummy=1;i<x-1;i++)
            {
                dummy*=10;
            }
            temp=count/dummy;
            if(temp==4||temp==7)
            {
                temp=temp;
            }
            else
            {
                printf("NO");
                exit(0);
            }
            count=count-temp*dummy;
            if(count<10)
            {
                if(count==7||count==4)
                {
                    printf("YES");
                    exit(0);
                }
                else
                {
                    printf("NO");
                    exit(0);
                }
            }
            x--;
        }while(x>=0);
    }
    else if(count<10)
    {
        if(count==7||count==4)
        {
            printf("YES");
        }
        else
        {
            printf("NO");
        }
    }
}
