#include<stdio.h>
int main(void)
{
    int t,i,j,sum1=0,sum2=0,temp;
    scanf("%d",&t);
    int array[t],answers[t];
    for(i=0;i<t;i++)
    {
        scanf("%d",&array[i]);
    }
    for(j=0;j<t;j++)
    {
        sum1=0;
        sum2=0;
        if((array[j]/2)%2==0)
        {
        for(i=1,temp=1;i<=array[j]/2;i++)
        {
            temp*=2;
            if(i%2!=0)
            {
                sum1+=temp;
            }
            else
            {
                sum2+=temp;
            }
        }
        for(i=array[j]/2+1,temp;i<=array[j];i++)
        {
            temp*=2;
            if(i%2==0)
            {
                sum1+=temp;
            }
            else
            {
                sum2+=temp;
            }
        }
        }
    else
    {
        for(i=1,temp=1;i<=array[j]/2+1;i++)
        {
            temp*=2;
            if(i%2!=0)
            {
                sum1+=temp;
            }
            else
            {
                sum2+=temp;
            }
        }
        for(i=array[j]/2+2,temp;i<=array[j];i++)
        {
            temp*=2;
            if(i%2==0)
            {
                sum1+=temp;
            }
            else
            {
                sum2+=temp;
            }
        }
    }
    if(sum1>sum2)
    {
        answers[j]=sum1-sum2;
    }
    else
        answers[j]=sum2-sum1;
    }
    for(i=0;i<t;i++)
    {
        printf("%d\n",answers[i]);
    }
    return 0;
}
