#include<stdio.h>
int main(void)
{
    long int i,t,a,b,c,d,result,sig,x,y,z,x1,y1,z1,z2,temp,max,min;
    scanf("%d",&t);
    long int answers[t][3];
    for(i=0,sig=0;i<t;i++)
    {
        scanf("%ld %ld %ld %ld",&a,&b,&c,&d);
        x=a,y=b,z=c;
        x1=a,y1=b,z1=c,z2=d;
        if(x+y>z||x+z>y||y+z>x)
        {
        if(x+y<z)
        {
            temp=z-x-y+1;
            z-=temp;
            if(z>=c&&z<=d)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+y==z)
        {
            z-=1;
        }
        if(x+z>y)
        {
            temp=y-z-x+1;
            y-=temp;
            if(y>=b&&y<=c)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+z==y)
        {
            y-=1;
        }
        if(y+z<x)
        {
            temp=x-y-z+1;
            x-=temp;
            if(x>=a&&x<=b)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(z+y==x)
        {
            x-=1;
        }
        }
        if(sig>0)
        {
            sig=0;
            x=x1,y=z2,z=z1;
            if(x+y>z||x+z>y||y+z>x)
        {
        if(x+y<z)
        {
            temp=z-x-y+1;
            z-=temp;
            if(z>=c&&z<=d)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+y==z)
        {
            z-=1;
        }
        if(x+z>y)
        {
            temp=y-z-x+1;
            y-=temp;
            if(y>=b&&y<=c)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+z==y)
        {
            y-=1;
        }
        if(y+z<x)
        {
            temp=x-y-z+1;
            x-=temp;
            if(x>=a&&x<=b)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(z+y==x)
        {
            x-=1;
        }
        }
        }
        if(sig>0)
        {
            x=y1,y=z1,z=z2;
            sig=0;
            if(x+y>z||x+z>y||y+z>x)
        {
        if(x+y<z)
        {
            temp=z-x-y+1;
            z-=temp;
            if(z>=c&&z<=d)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+y==z)
        {
            z-=1;
        }
        if(x+z>y)
        {
            temp=y-z-x+1;
            y-=temp;
            if(y>=b&&y<=c)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(x+z==y)
        {
            y-=1;
        }
        if(y+z<x)
        {
            temp=x-y-z+1;
            x-=temp;
            if(x>=a&&x<=b)
            {
                sig=sig;
            }
            else
            {
                sig++;
            }
        }
        else if(z+y==x)
        {
            x-=1;
        }
        }
        }
        min=x<y?x<z?x:z:y<z?y:z;
        max=x>y?x>z?x:z:y>z?y:z;
        temp=x+y+z-min-max;
        answers[i][0]=min;
        answers[i][1]=temp;
        answers[i][2]=max;
    }
    for(i=0;i<t;i++)
    {
        printf("%ld %ld %ld\n",answers[i][0],answers[i][1],answers[i][2]);
    }
}

